### PR TITLE
fixing a typo

### PR DESCRIPTION
**Pull request by Akatsuki-Ryu**
i recreated the pull request . thank you

### CODE REVIEW

**Comment by MurphyKyle** [comment]
Thanks!

**Comment by Akatsuki-Ryu** [comment]
i am thinking to add some stuff to the spectator logic. like, when there is a spectator, we make the smooth bigger and also aiming at different body parts randomly. that will look more natural. what do you think ?

**Comment by MurphyKyle** [comment]
Hey!
I think that is a good idea, but is there a way to see who is spectating
YOU specifically? Or is it still just who is spectating YOUR TEAM?

**Comment by Akatsuki-Ryu** [comment]
accoording to the source code , we can only know how many enemy is watching you , or how many of your team mate is watching you .  i already made a very simple version of the dynamic aiming . but i will need to make a bit more logic and integrate into the spectator and safety logic later.

**Comment by KingRikkie** [comment]
> 
> 
> accoording to the source code , we can only know how many enemy is watching you , or how many of your team mate is watching you . i already made a very simple version of the dynamic aiming . but i will need to make a bit more logic and integrate into the spectator and safety logic later.

Since a few weeks spectator count is not networked anymore so all you can do is hook the msg queue to get notfied when someone went into spectator mode. As that also happens by default when you finish off a team it isn't that helpful.

**Comment by Akatsuki-Ryu** [comment]
my experience is that when the flag is bigger than 3 , definately people are watching . when you are in the firerange alone . the flag might also get to 1 if you kill the dummys . but i am introducing a dynamic aiming to make it a bit less "spicy" . i am not sure shall i put it on the guest side or on the dma . it doesnt matter too much i would say . lets see what will come after the new patch is released :D

**Comment by MurphyKyle** [comment]
It will be on both if you want it configurable. I would just jabber it on
host side.

**Comment by Akatsuki-Ryu** [comment]
> > 
> 
> > 
> 
> > accoording to the source code , we can only know how many enemy is watching you , or how many of your team mate is watching you . i already made a very simple version of the dynamic aiming . but i will need to make a bit more logic and integrate into the spectator and safety logic later.
> 
> 
> 
> Since a few weeks spectator count is not networked anymore so all you can do is hook the msg queue to get notified when someone went into spectator mode. As that also happens by default when you finish off a team it isn't that helpful.

Thank you very much for exchanging knowledge. So I think it means there are people watching. But not necessarily watching you. Then I guess then it is most likely safe to leave the hacks options on. Just dont go rage and it is fine.

**Comment by Akatsuki-Ryu** [comment]
The dynamic aiming I was looking to is to dynamically change the bone target to aim. That can be done on guest to send the bone value dynamically.

**Comment by KingRikkie** [comment]
> The dynamic aiming I was looking to is to dynamically change the bone target to aim. That can be done on guest to send the bone value dynamically.

Is it safe though? Last time I tried the aimbot (very high smoothing, low FOV) I got banned about 48h later.

**Comment by MurphyKyle** [comment]
Yes, the auto bone switch is a good idea.
Bans are hard to pinpoint what went wrong. With this cheat it is usually
related to the overlay more than the aimbot itself, although blatant
beaming will get you banned pretty quickly.

For example: I used this on two accounts with the same VM over about a
month or two.
A couple of weeks ago I got banned *the morning after* I got a 22kill 4200
dmg game, but the other account I cheated on is still not banned. I do not
use any overlays.

**Comment by KingRikkie** [comment]
Yea I think they stepped up aimbot detection a lot. We might get away with a Recoil Control System (RCS) instead (reduces recoil of guns by x%) as full no recoil isn't safe either

**Comment by MurphyKyle** [comment]
Right.
Maybe something else to think about around the bone switching stuff is to
just not have any aim adjustments within a certain area. That way you would
be vastly decreasing the amount of memory writes you are doing.
Implementation is left to you!  😉

**Comment by Akatsuki-Ryu** [comment]
> > The dynamic aiming I was looking to is to dynamically change the bone target to aim. That can be done on guest to send the bone value dynamically.
> 
> Is it safe though? Last time I tried the aimbot (very high smoothing, low FOV) I got banned about 48h later.

had been playing for 20+ hours with the code I made . still safe . but I dont go toxic and kill lot of people . my smooth is 80 , fov 10.f , not sure about the season 9 tho . I have no recoil.

**Comment by Akatsuki-Ryu** [comment]
> Yes, the auto bone switch is a good idea. Bans are hard to pinpoint what went wrong. With this cheat it is usually related to the overlay more than the aimbot itself, although blatant beaming will get you banned pretty quickly. For example: I used this on two accounts with the same VM over about a month or two. A couple of weeks ago I got banned *the morning after* I got a 22kill 4200 dmg game, but the other account I cheated on is still not banned. I do not use any overlays.
> […](#)

I am running on Nvidia card , and it naturally come with the overlay . then I switch to this code base , so I go without any overlay . for the dynamic aiming , you can find in my repo .
for 4200 dmg , it is really big and toxic . I got also banned after I got some rage killings . mainly it was reported by players. the codebase I believe is safe . just dont do too toxic .

**Comment by Akatsuki-Ryu** [comment]
> Right. Maybe something else to think about around the bone switching stuff is to just not have any aim adjustments within a certain area. That way you would be vastly decreasing the amount of memory writes you are doing. Implementation is left to you! 😉
> […](#)

the user playing the game is any writing to the memory . I dont think it matters . if the writing method is safe . it is safe . . doesn't matter how many it writes . when you are playing , it writes all the time after all .

**Comment by KingRikkie** [comment]
> > > The dynamic aiming I was looking to is to dynamically change the bone target to aim. That can be done on guest to send the bone value dynamically.
> > 
> > 
> > Is it safe though? Last time I tried the aimbot (very high smoothing, low FOV) I got banned about 48h later.
> 
> I have no recoil.

so you are using no recoil? That cant be safe

**Comment by Akatsuki-Ryu** [comment]
hmm , yes , this account is 50+ hours play time and still going , with all possible options on . fov 10, smooth at 80, dynamic aiming I put it on like 1 week ago . but now I am playing without dynamic aiming .

**Comment by KingRikkie** [comment]
> hmm , yes , this account is 50+ hours play time and still going , with all possible options on . fov 10, smooth at 80, dynamic aiming I put it on like 1 week ago . but now I am playing without dynamic aiming .
> but I almost never rage . so the kd rate is round 1, max dmg / round was 1900 ,avg dmg is 500ish

Ah I am so sorry, I thought the **No Recoil** would be separate from the aimbot, like writing sway-angles to 0 so all guns would have zero recoil without any aimbot.

**Comment by Akatsuki-Ryu** [comment]
I think i will make a better logic for aim bot and logics . including dynamic bone . dynamic fov, dynamic smooth . 
currently the spectator counting is kind not working , it is always showing 0 .. can any of you check ?

**Comment by KingRikkie** [comment]
> 
> 
> I think i will make a better logic for aim bot and logics . including dynamic bone . dynamic fov, dynamic smooth .
> currently the spectator counting is kind not working , it is always showing 0 .. can any of you check ?

You can't get spectators anymore, all you can get is a list off all players currently spectating *someone* on the server so it's basically useless.

I am currently looking into implementing a Recoil Control System but it is a bit hard externally without a proper aimpoint.

**Comment by MurphyKyle** [comment]
Can you not just set 0, 0, as aimpoint and then subtract your recoil angles
out of current view angles?

**Comment by KingRikkie** [comment]
> Can you not just set 0, 0, as aimpoint and then subtract your recoil angles out of current view angles?
> 
You can do it with view angles alone, I just pushed an update: 
https://github.com/KingRikkie/apex_dma_kvm_pub/blob/no-esp-overlay/apex_dma/apex_dma.cpp#L351

**Comment by Akatsuki-Ryu** [comment]
the bullet speed value is always 0 , it was working in season 8 with the aiming predictions , please exchange info if you happen to know anyhting .  i will take a look at kingrikkie's code later . thanks for the update

**Comment by MurphyKyle** [comment]
Nice work, king! Looks like updating vmread wasnt too difficult afterall. I
figured as much but I have 0 experience and 0 motivation to dig through it
🙃

**Comment by KingRikkie** [comment]
> Nice work, king! Looks like updating vmread wasnt too difficult afterall. I figured as much but I have 0 experience and 0 motivation to dig through it upside_down_face
>

well my next step is to port it to .NET 5 (C#) and use memflow instead of vmread

**Comment by MurphyKyle** [comment]
What's the difference, really?? And it'll be C# on Linux? Not sure ive
heard of it haha

**Comment by Akatsuki-Ryu** [comment]
> > Nice work, king! Looks like updating vmread wasnt too difficult afterall. I figured as much but I have 0 experience and 0 motivation to dig through it upside_down_face
> 
> well my next step is to port it to .NET 5 (C#) and use memflow instead of vmread

unfortunately , I dont have enough knowledge for this ... too bad . but i am very much looking forward to read the your code .

**Comment by KingRikkie** [comment]
> 
> What's the difference, really?? And it'll be C# on Linux? Not sure ive heard of it haha
> 

I absolutely despise C++ and its terrible syntax. .NET Core is on Linux since Microsoft made the entire framework open source and .NET 5 is the 4th iteration of .NET Core. 
:NET has come a very, very long way in recent years. Here is a good outline of what have been done for performance optimization within the last 6 months: https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/

**Comment by MurphyKyle** [comment]
Ahh cool, last I checked core was still using framework 2.0 hahaha

**Comment by Akatsuki-Ryu** [comment]
@KingRikkie I checked out the recoil script , it was sooo cool ! greate job man  . i am thinking to integrate it into this codebase and make it into a seperate option .

**Comment by MurphyKyle** [comment]
> > What's the difference, really?? And it'll be C# on Linux? Not sure ive heard of it haha
> 
> I absolutely despise C++ and its terrible syntax. .NET Core is on Linux since Microsoft made the entire framework open source and .NET 5 is the 4th iteration of .NET Core.
> .NET has come a very, very long way in recent years. Here is a good outline of what have been done for performance optimization within the last 6 months: https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/

King, did you plan on making a couple of pull requests at all? I was thinking of at least one for the vmread update assuming it still works on 1909 like before. And did you cover ALL changes to update it or just the necessary ones for this project?

Also, what is the current state of your recoil control system? I do want to cherry pick it into my branch. I will set it up so that the user can toggle it and aimbot independently of eachother.

**Comment by Akatsuki-Ryu** [comment]
I am working on this right now. I will integrate the recoil control to your code base

**Comment by Akatsuki-Ryu** [comment]
i tested the new vmread on 1909 . it works . 

@KingRikkie  you are right king . it might be risky to have 100% no recoil . i was running no recoil on my dynamic aim logic . to add a bit more "noise" when aiming . 

@MurphyKyle i will make a pull request later . as king removed the aimbot logic. personally i would like to have them both .

**Comment by MurphyKyle** [comment]
> I am not going to do PRs, if you want you can cherrypick it yourself. I did not test it on 1909, I copied over all changes.
> 
> The RCS is currently in testing, I fixed a problem with semi-auto rifles yesterday but it's not perfect yet. Also from time to time it feels a bit sluggish, I don't know if that's just the remaining recoil or if the sway angles have some weird edge cases. I would like to **not** add this to the main branch/repo or we'll have too much exposure due to clueless users running around with 100% no recoil.

Sounds good, how do you think it is any different than now? The clueless already run around with aggressive aimbot + recoil control on.

**Comment by KingRikkie** [comment]
> > I am not going to do PRs, if you want you can cherrypick it yourself. I did not test it on 1909, I copied over all changes.
> > The RCS is currently in testing, I fixed a problem with semi-auto rifles yesterday but it's not perfect yet. Also from time to time it feels a bit sluggish, I don't know if that's just the remaining recoil or if the sway angles have some weird edge cases. I would like to **not** add this to the main branch/repo or we'll have too much exposure due to clueless users running around with 100% no recoil.
> 
> Sounds good, how do you think it is any different than now? The clueless already run around with aggressive aimbot + recoil control on.

Those get banned within a few weeks, since last update lots of rage hackers are crying about getting banned for generic aimbot detection. I see very very few big provider hacks with an RCS, almost none actually. The RCS does not trigger APEX' server sided aimbot machine learning network yet even though we are using a similar loop + write view angles. If we have too many people using it they'll upgrade their detection and we'll be left with nothing.

**Comment by MurphyKyle** [comment]
Gotcha. I did not plan to push to the actual MisterY52/apex_dma_kvm_pub:master, but are you okay with it being public on my fork? If not that's all okay too.

**Comment by Akatsuki-Ryu** [comment]
i made a pull request . will test out that branch later . @KingRikkie @MurphyKyle

**Comment by MurphyKyle** [comment]
Hey @Akatsuki-Ryu I won't accept that PR since it has all the changes in one and it doesn't implement the RCS the way I mentioned before, although that does seem to follow King's recommendations nicely.
If you wanted to, you can create separate pull requests: One for the offsets update portion, one for vmread and gitignore, and I can cherry-pick the main RCS logic.

**Comment by Akatsuki-Ryu** [comment]
sure , i can sepreate to multiple PR. so i will do one for offset , one for gitignore , one fo RCS , one for vmread  .

**Comment by MurphyKyle** [comment]
Sorry I mis-understood your implementation a bit. I do see how in your source code the two can be configured independently of each other.

My thought process was to just implement it into the aimbot loop with a simple check on whether RCS is on as a minor additional adjustment to the aim angles produced by aimbot (or not).

**Comment by Akatsuki-Ryu** [comment]
the aim and RCS are separate for now. and they are all writing to the view angle (should not be on at the same time ) , so if we want to have them both available , we need to do some deeper integration , put RCS checks into the aim loop .

**Pull request merged**
